### ISSUE TITLE
retrain lightglue

### ISSUE THREAD

**Issue by noahzn** [georg-bn/rotation-steerers#8]
Hi, @georg-bn , as you said in one issue "One could also retrain lightglue for our descriptors from settings B and C". How can I achieve this? I have trained XFeat with a learned steerer, how can I use the descriptors to re-train lightglue? Could you provide a code script to show how to combine the learned steerer with the original descriptors of XFeat? Thanks in advance.

My understanding is that once I have trained XFeat with Steerer, I can extract keypoints on images using XFeat and then get the 'permuted' descriptors using Steerer, and then use these descriptors to train LightGlue, is my understanding correct?

**Comment by georg-bn** [comment]
If you have retrained XFeat then you can't use the learned steerer with the original descriptors. Maybe I'm misunderstanding.

Do you want to train LightGlue on data with arbitrary rotations? Otherwise, for just training on MegaDepth, you can train LightGlue on the descriptors from your retrained XFeat. Then you can use the steerer on the descriptors at inference. But you will have to rerun LightGlue for every steered rotation for rotation invariant matching at inference.

**Comment by noahzn** [comment]
Thanks for your reply. 

> But you will have to rerun LightGlue for every steered rotation for rotation invariant matching at inference.

Does it mean that for each image, I need to infer LightGlue several times?

**Comment by noahzn** [comment]
I want to rephrase my question, and maybe I misunderstand the usage of steerer.
I retrained XFeat and a learned steerer on my own data using homography transformation. After that, I want to train LightGlue based on my re-trained XFeat. Can I only use the learned steerer in the inference?

**Comment by georg-bn** [comment]
The standard way of using a steerer would be to modify the descriptors so that they correspond to rotated images. This has to be done before feeding the descriptors into LightGlue, unless LightGlue is modified to itself use the steerer in some way. How that should be done is an open question. 

If we consider ordinary LightGlue, then LightGlue expects upright descriptors and the steerer has to be applied before LightGlue. If the relative rotation between images is unknown, then several rotations have to be tried. Potentially one could also instead use ordinary (cheaper) mnn-matching to determine the correct relative rotation using steerers, before feeding correctly steered descriptors into LightGlue.

**Comment by noahzn** [comment]
Thanks for your clarification.
